### PR TITLE
Convert fit-form component to classic layout

### LINKED ISSUE #47: Unusable in apps using Pods file layout with a pod module prefix
According to the ember guides https://cli.emberjs.com/release/advanced-use/project-layouts/
```
Addons should only use the classic structure for compatibility with either classic or pods-based consuming applications.
```

ember-fit-form has it's main fit-form component strucutred as a pod, rather than the classic layout. Any consuming app that uses a pod-module-prefix will be unable to resolve the fit-form component. 

Suggested Fix:
```
addon
├── components/fit-form
     ├── template.hbs
     └── component.js
```
should become
```
addon
├── components
|   └── fit-form.js
├── templates
    └── components/fit-form.hbs
```

### PR DESCRIPTION
**Pull request by steveszc**
## Purpose
Fixes #47 

## Approach
Converts fit-form component from pods layout to classic layout

## Learning
https://cli.emberjs.com/release/advanced-use/project-layouts/

> Addons should only use the classic structure for compatibility with either classic or pods-based consuming applications.

### CODE REVIEW

**Comment by steveszc** [comment]
@flexyford Mind giving this a quick look?

**Comment by flexyford** [comment]
Happy to merge this, but a couple of tests relied on pod structure. Mind fixing those up as well?

**Comment by steveszc** [comment]
@flexyford Oops I missed the required updates to the /app directory files.
Looks like theres still one test failing now, and its also failing locally. 
```
Unit | Component | form-adapters/ember-changeset/ember-changeset-validations > with a model with validations > validate the form: validating an invalid form fails the validation step
```
Not really clear to me why that particular assertion would fail due to these changes.

**Comment by flexyford** [comment]
After looking into this, we found that this test is failing in `master` and we suspect it is due to an bugfix in https://github.com/poteto/ember-changeset/pull/378.

We are going to merge to file structure update and fix the test prior to a `2.0.0` release.

**Pull request merged**
